spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kendo_result_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: my-strong-secret-key-which-is-32bytes!
  expiration: 86400000
